//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>CV Overview</summary>
	[PublishedContentModel("cvOverview")]
	public partial class CvOverview : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cvOverview";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CvOverview(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CvOverview, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Employer Description
		///</summary>
		[ImplementPropertyType("employerDescription")]
		public IHtmlString EmployerDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("employerDescription"); }
		}

		///<summary>
		/// Employer Name
		///</summary>
		[ImplementPropertyType("employerName")]
		public string EmployerName
		{
			get { return this.GetPropertyValue<string>("employerName"); }
		}
	}
}
